services:

  blog_db:
    image: postgres:16.4
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always
    env_file: .env
    volumes:
      - ./blog_db:/var/lib/postgresql/data

  blog_server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - blog_db
    restart: always


volumes:
  blog_db:
